# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='poke_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam2.User'),
        ),
    ]
